# -*- coding: utf-8 -*-
"""Gangnam_children

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dI9RK2GABVfzzS4z7W5iqQA3J_ogeJo_
"""

import folium
from folium import plugins
import numpy as np
import os
import pandas as pd

Gangnam=pd.read_csv('seoul.csv',encoding='cp949')

Gangnam

A1=Gangnam.경도.min()
A2=Gangnam.경도.max()
B1=Gangnam.위도.min()
B2=Gangnam.위도.min()

length=len(Gangnam)

N = length

data = np.array(
[
np.random.uniform(low=B1, high=B2, size=N),
np.random.uniform(low=A1, high=A2, size=N),
]
).T
print(data)

popups = [str(i) for i in range(N)]

m = folium.Map([37.49701984561038, 127.06804545662564], zoom_start=10)
plugins.MarkerCluster(data,popups=popups).add_to(m)
m

m.save('Gangnam_children.html')

import os
path = os.getcwd()
os.listdir(path)

